#!/bin/bash
#colors
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
NC='\033[0m'

# Background colors
BG_BLACK='\033[40m'
BG_RED='\033[41m'
BG_GREEN='\033[42m'
BG_YELLOW='\033[43m'
BG_BLUE='\033[44m'
BG_PURPLE='\033[45m'
BG_CYAN='\033[46m'
BG_WHITE='\033[47m'

r_echo() {
  echo -e "${RED}$1${RESET}"
}
g_echo() {
  echo -e "${GREEN}$1${NC}"
}
y_echo() {
  echo -e "${YELLOW}$1${NC}"
}
c_echo() {
  echo -e "${CYAN}$1${RESET}"
}
