#!/bin/bash
source "$SIKAR_SYSTEM_DIR/colours"

SIKAR_DIR="$HOME/Workspace/Sikar"
SIKAR_SYSTEM_DIR="$(dirname "$(readlink -f "$0")")"
SIKAR_SOURCE_DIR="$SIKAR_SYSTEM_DIR/source"
JAVA_IDE="IntelliJ IDEA CE"