#!/bin/bash

# Check if a project directory is provided as an argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 <project_directory>"
    exit 1
fi

#enhance in future with multiple IDEs support
ide="IntelliJ IDEA CE"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project=*)
      project="${1#*=}"
      ;;
    --ide=*)
      ide="${1#*=}"
      ;;
    *)
      echo "Invalid option: $1"
      exit 1
      ;;
  esac
  shift
done

# Check if the project directory exists
if [ ! -d "$project" ]; then
    echo "Project directory '$project' does not exist."
    exit 1
fi

# Open the project in IntelliJ IDEA
echo "Opening project in IntelliJ IDEA..."
open -a "$ide" "$project"